In [20]:
# Importación de librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier  # ANN
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC  # SVM
from sklearn.metrics import accuracy_score
from datetime import datetime as dt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [15]:
# Cargar los datos
dataset = pd.read_csv('../data/processed/features_for_model.csv')
dataset.head()

Unnamed: 0        Open        High         Low       Close    Volume  \
0           0  137.610001  137.789993  136.440002  137.059998   7037300   
1           1  137.029999  137.589996  136.190002  137.429993   6448600   
2           2  137.800003  138.220001  137.639999  137.979996   8776000   
3           3  138.389999  138.940002  137.869995  138.559998   5220500   
4           4  138.029999  138.419998  137.970001  138.210007  10106700   

   Dividends  Stock Splits  Capital Gains  Daily Change  Price Range    Return  
0        0.0           0.0            0.0      1.349991    -0.550003  0.000000  
1        0.0           0.0            0.0      1.399994     0.399994  0.002700  
2        0.0           0.0            0.0      0.580002     0.179993  0.004002  
3        0.0           0.0            0.0      1.070007     0.169998  0.004204  
4        0.0           0.0            0.0      0.449997     0.180008 -0.002526

In [16]:
#Dividir los datos en características (X) y etiquetas (y)
# Supongamos que la columna 'fraude' es nuestra variable objetivo (0: no fraude, 1: fraude)
X = dataset.drop('Volume', axis=1)  # Características
y = dataset['Volume']               # Etiquetas

In [26]:
# Dividir los datos en conjuntos de entrenamiento y prueba (80% - 20%)
# Dividir el conjunto de datos en entrenamiento y prueba
from sklearn.metrics import classification_report, confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### 1. Arboles de decisión

In [28]:
# Inicializar y entrenar el modelo de árbol de decisión
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)

# Predicción
y_pred_1 = modelo.predict(X_test)

# Evaluación del modelo
print("Modelo 1 - Árbol de Decisión Básico")
print(classification_report(y_test, y_pred_1))
print(confusion_matrix(y_test, y_pred_1))

Modelo 1 - Árbol de Decisión Básico
              precision    recall  f1-score   support

     2445100       0.00      0.00      0.00       0.0
     2620600       0.00      0.00      0.00       0.0
     2672800       0.00      0.00      0.00       1.0
     2971100       0.00      0.00      0.00       1.0
     3203800       0.00      0.00      0.00       1.0
     3292700       0.00      0.00      0.00       1.0
     3374200       0.00      0.00      0.00       0.0
     3434100       0.00      0.00      0.00       0.0
     3548800       0.00      0.00      0.00       0.0
     3645800       0.00      0.00      0.00       1.0
     3760700       0.00      0.00      0.00       0.0
     3768600       0.00      0.00      0.00       0.0
     3797900       0.00      0.00      0.00       0.0
     3809700       0.00      0.00      0.00       1.0
     3847700       0.00      0.00      0.00       0.0
     3874800       0.00      0.00      0.00       0.0
     3877700       0.00      0.00      0.00  

c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, m

In [29]:
y_predicst=modelo.predict(X_test)
accuracy_score(y_test,y_predicst)

0.0

### 2. Random Forest

In [30]:
# Crear el modelo de Random Forest con hiperparámetros básicos
model4 = RandomForestClassifier(n_estimators=50, random_state=42)

# Entrenar el modelo
model4.fit(X_train, y_train)

# Predecir los resultados en el conjunto de prueba
y_pred = model4.predict(X_test)

# Evaluar el modelo
print("Matriz de Confusión:")
print(confusion_matrix(y_test, y_pred))

print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred))

print("\nPrecisión del Modelo:")
print(accuracy_score(y_test, y_pred))

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Reporte de Clasificación:
              precision    recall  f1-score   support

     2672800       0.00      0.00      0.00       1.0
     2971100       0.00      0.00      0.00       1.0
     3071300       0.00      0.00      0.00       0.0
     3203800       0.00      0.00      0.00       1.0
     3205500       0.00      0.00      0.00       0.0
     3292700       0.00      0.00      0.00       1.0
     3434100       0.00      0.00      0.00       0.0
     3634800       0.00      0.00      0.00       0.0
     3645800       0.00      0.00      0.00       1.0
     3654900       0.00      0.00      0.00       0.0
     3662500       0.00      0.00      0.00       0.0
     3713400       0.00      0.00      0.00       0.0
     3797900       0.00      0.00      0.00       0.0
     3809700       0.00      0.00      0.00       1.0
     3847700       0.

c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, m

### 3. Naives Bayes

In [31]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler

# Normalizar las características para Naive Bayes
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Crear el modelo de Naive Bayes
modelo6 = GaussianNB()

# Entrenar el modelo
modelo6.fit(X_train, y_train)

# Predecir los resultados en el conjunto de prueba
y_pred = modelo6.predict(X_test)

# Evaluar el modelo
print("Matriz de Confusión:")
print(confusion_matrix(y_test, y_pred))

print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred))

print("\nPrecisión del Modelo:")
print(accuracy_score(y_test, y_pred))

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Reporte de Clasificación:
              precision    recall  f1-score   support

     2672800       0.00      0.00      0.00       1.0
     2971100       0.00      0.00      0.00       1.0
     3203800       0.00      0.00      0.00       1.0
     3292700       0.00      0.00      0.00       1.0
     3645800       0.00      0.00      0.00       1.0
     3809700       0.00      0.00      0.00       1.0
     4029100       0.00      0.00      0.00       1.0
     4052900       0.00      0.00      0.00       1.0
     4167000       0.00      0.00      0.00       1.0
     4185000       0.00      0.00      0.00       1.0
     4224700       0.00      0.00      0.00       1.0
     4301700       0.00      0.00      0.00       1.0
     4321100       0.00      0.00      0.00       1.0
     4337700       0.00      0.00      0.00       1.0
     4398400       0.

c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, m

### 4. Suport Vector Machine (SVM)

In [32]:
# Normalizar las características para mejorar el rendimiento de SVM
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Crear el modelo SVM con un kernel lineal
model = SVC(kernel='linear', C=1.0, random_state=42)

# Entrenar el modelo
model.fit(X_train, y_train)

# Predecir los resultados en el conjunto de prueba
y_pred = model.predict(X_test)

# Evaluar el modelo
print("Matriz de Confusión:")
print(confusion_matrix(y_test, y_pred))

print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred))

print("\nPrecisión del Modelo:")
print(accuracy_score(y_test, y_pred))

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Reporte de Clasificación:
              precision    recall  f1-score   support

     2672800       0.00      0.00      0.00       1.0
     2971100       0.00      0.00      0.00       1.0
     3071300       0.00      0.00      0.00       0.0
     3203800       0.00      0.00      0.00       1.0
     3292700       0.00      0.00      0.00       1.0
     3434100       0.00      0.00      0.00       0.0
     3456300       0.00      0.00      0.00       0.0
     3645800       0.00      0.00      0.00       1.0
     3797900       0.00      0.00      0.00       0.0
     3809700       0.00      0.00      0.00       1.0
     3828800       0.00      0.00      0.00       0.0
     3847700       0.00      0.00      0.00       0.0
     3877700       0.00      0.00      0.00       0.0
     3998500       0.00      0.00      0.00       0.0
     4002600       0.

c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, m

In [41]:
pip install tensorflow

   ---------------------------------------- 0.0/390.2 MB ? eta -:--:--
   ---------------------------------------- 1.3/390.2 MB 7.5 MB/s eta 0:00:52
   ---------------------------------------- 2.1/390.2 MB 6.2 MB/s eta 0:01:03
   ---------------------------------------- 3.1/390.2 MB 5.1 MB/s eta 0:01:16
   ---------------------------------------- 3.9/390.2 MB 4.9 MB/s eta 0:01:19
   ---------------------------------------- 4.7/390.2 MB 4.8 MB/s eta 0:01:22
    --------------------------------------- 5.5/390.2 MB 4.6 MB/s eta 0:01:24
    --------------------------------------- 6.3/390.2 MB 4.4 MB/s eta 0:01:27
    --------------------------------------- 7.1/390.2 MB 4.3 MB/s eta 0:01:29
    --------------------------------------- 7.9/390.2 MB 4.2 MB/s eta 0:01:32
    --------------------------------------- 8.7/390.2 MB 4.1 MB/s eta 0:01:33
    --------------------------------------- 9.4/390.2 MB 4.1 MB/s eta 0:01:33
   - -------------------------------------- 10.2/390.2 MB 4.1 MB/s eta 

  You can safely remove it manually.
  You can safely remove it manually.


### 5. Redes Neuronales

In [42]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Normalizar las características (esto es importante para redes neuronales)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Construcción de un modelo simple de red neuronal
modelo_nn = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')  # Cambia según el tipo de problema
])

# Compilar el modelo
modelo_nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Entrenar el modelo
modelo_nn.fit(X_train_scaled, y_train, epochs=10, batch_size=32, validation_data=(X_test_scaled, y_test))

# Evaluar el modelo
y_pred_nn = (modelo_nn.predict(X_test_scaled) > 0.5).astype("int32")
print(classification_report(y_test, y_pred_nn))
print(confusion_matrix(y_test, y_pred_nn))

c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.0000e+00 - loss: -3873699.5000 - val_accuracy: 0.0000e+00 - val_loss: -13748442.0000
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: -20570234.0000 - val_accuracy: 0.0000e+00 - val_loss: -43781284.0000
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: -60463856.0000 - val_accuracy: 0.0000e+00 - val_loss: -115027528.0000
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: -146368096.0000 - val_accuracy: 0.0000e+00 - val_loss: -263976272.0000
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: -322538368.0000 - val_accuracy: 0.0000e+00 - val_loss: -532952640.0000
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: -642715968.0000 - val_accuracy: 0.0000e+00 - val_loss: -962108160.0000
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: -1127080064.

c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\DELL LATITUDE\anaconda3\envs\venv-churning-model\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, m